spring:
  datasource:
    one:
      url: jdbc:mysql://localhost:3306/springlab?useSSL=false
      username: root
      password: java1234
      type: com.alibaba.druid.pool.DruidDataSource
    two:
      url: jdbc:mysql://localhost:3306/newbee_mall_db?useSSL=false
      username: root
      password: java1234
      type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql://localhost:3306/springlab?useSSL=false
#    username: root
#    password: java1234
#    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:mappertwo/*.xml
