mybatis:
  type-aliases-package: cn.zach.batchinsert.entity
  mapper-locations: classpath:mapper/*.xml
spring:
  datasource:
    url: jdbc:mysql://1.117.169.244:3306/batch_insert?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: java1234