spring:
  security:
    user:
      name: zach
      password: java123456
      roles: admin
  datasource:
    url: jdbc:mysql://localhost:3306/springlab?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: java1234
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.zach.springsecurity.entity
logging:
  level:
    cn.zach.springsecurity.mapper: debug